<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRTmOwjx\srcProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRTmOwjx/srcProdProjectContainer.php') {
    touch(__DIR__.'/ContainerRTmOwjx.legacy');

    return;
}

if (!\class_exists(srcProdProjectContainer::class, false)) {
    \class_alias(\ContainerRTmOwjx\srcProdProjectContainer::class, srcProdProjectContainer::class, false);
}

return new \ContainerRTmOwjx\srcProdProjectContainer(array(
    'container.build_hash' => 'RTmOwjx',
    'container.build_id' => 'e0cbf35c',
    'container.build_time' => 1522618865,
));
