<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\ServiceValueResolver.php';

return $this->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\PagesController:aide' => function () {
    return ($this->privates['service_locator.6U4AvGX'] ?? $this->load(__DIR__.'/getServiceLocator_6U4AvGXService.php'));
}, 'App\\Controller\\PagesController:apropos' => function () {
    return ($this->privates['service_locator.THq2EBF'] ?? $this->load(__DIR__.'/getServiceLocator_THq2EBFService.php'));
}, 'App\\Controller\\PagesController:chercher' => function () {
    return ($this->privates['service_locator.seIhI4_'] ?? $this->load(__DIR__.'/getServiceLocator_SeIhI4Service.php'));
}, 'App\\Controller\\PagesController:concepteur' => function () {
    return ($this->privates['service_locator.THq2EBF'] ?? $this->load(__DIR__.'/getServiceLocator_THq2EBFService.php'));
}, 'App\\Controller\\PagesController:contact' => function () {
    return ($this->privates['service_locator.THq2EBF'] ?? $this->load(__DIR__.'/getServiceLocator_THq2EBFService.php'));
}, 'App\\Controller\\PagesController:index' => function () {
    return ($this->privates['service_locator.Xbt2C5t'] ?? $this->load(__DIR__.'/getServiceLocator_Xbt2C5tService.php'));
}, 'App\\Controller\\SavePathController:index' => function () {
    return ($this->privates['service_locator.SyY2KNI'] ?? $this->load(__DIR__.'/getServiceLocator_SyY2KNIService.php'));
}, 'App\\Controller\\PagesController::aide' => function () {
    return ($this->privates['service_locator.6U4AvGX'] ?? $this->load(__DIR__.'/getServiceLocator_6U4AvGXService.php'));
}, 'App\\Controller\\PagesController::apropos' => function () {
    return ($this->privates['service_locator.THq2EBF'] ?? $this->load(__DIR__.'/getServiceLocator_THq2EBFService.php'));
}, 'App\\Controller\\PagesController::chercher' => function () {
    return ($this->privates['service_locator.seIhI4_'] ?? $this->load(__DIR__.'/getServiceLocator_SeIhI4Service.php'));
}, 'App\\Controller\\PagesController::concepteur' => function () {
    return ($this->privates['service_locator.THq2EBF'] ?? $this->load(__DIR__.'/getServiceLocator_THq2EBFService.php'));
}, 'App\\Controller\\PagesController::contact' => function () {
    return ($this->privates['service_locator.THq2EBF'] ?? $this->load(__DIR__.'/getServiceLocator_THq2EBFService.php'));
}, 'App\\Controller\\PagesController::index' => function () {
    return ($this->privates['service_locator.Xbt2C5t'] ?? $this->load(__DIR__.'/getServiceLocator_Xbt2C5tService.php'));
}, 'App\\Controller\\SavePathController::index' => function () {
    return ($this->privates['service_locator.SyY2KNI'] ?? $this->load(__DIR__.'/getServiceLocator_SyY2KNIService.php'));
})));
