<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.6U4AvGX' shared service.

return $this->privates['service_locator.6U4AvGX'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('doctrine' => function () {
    return ($this->services['doctrine'] ?? $this->getDoctrineService());
}, 'twig' => function () {
    return ($this->services['twig'] ?? $this->getTwigService());
}));
