<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.THq2EBF' shared service.

return $this->privates['service_locator.THq2EBF'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('doctrine' => function () {
    return ($this->services['doctrine'] ?? $this->getDoctrineService());
}, 'formFactory' => function () {
    return ($this->services['form.factory'] ?? $this->load(__DIR__.'/getForm_FactoryService.php'));
}, 'twig' => function () {
    return ($this->services['twig'] ?? $this->getTwigService());
}));
