<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.VOn0Nci' shared service.

return $this->privates['service_locator.VOn0Nci'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('formFactory' => function () {
    return ($this->services['form.factory'] ?? $this->load(__DIR__.'/getForm_FactoryService.php'));
}, 'mailer' => function () {
    return ($this->services['swiftmailer.mailer.default'] ?? $this->load(__DIR__.'/getSwiftmailer_Mailer_DefaultService.php'));
}, 'twig' => function () {
    return ($this->services['twig'] ?? $this->getTwigService());
}));
