<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5TLQOh6\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5TLQOh6/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container5TLQOh6.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container5TLQOh6\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container5TLQOh6\srcDevDebugProjectContainer(array(
    'container.build_hash' => '5TLQOh6',
    'container.build_id' => '90ca33f8',
    'container.build_time' => 1531409205,
));
