<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXHBYbEM\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXHBYbEM/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXHBYbEM.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXHBYbEM\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerXHBYbEM\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'XHBYbEM',
    'container.build_id' => '68deb18c',
    'container.build_time' => 1527277568,
));
