<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container86OzDq4\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container86OzDq4/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container86OzDq4.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container86OzDq4\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container86OzDq4\srcDevDebugProjectContainer(array(
    'container.build_hash' => '86OzDq4',
    'container.build_id' => 'dd1bd8e4',
    'container.build_time' => 1528623650,
));
